version: '3'

services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    environment:
      - VIRTUAL_HOST=vivid-api.com
      - DB_URL=mongodb://mongodb/vivid-db
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest

  load-balancer:
    image: dockercloud/haproxy
    links:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    restart: on-failure